name: Publish

on:
  push:
    tags:
      - v*
  workflow_dispatch:
    inputs:
      tag_name:
        required: true
        description: "The name of the tag and release that should be created."

jobs:
  build:
    runs-on: windows-latest

    steps:
    - uses: olegtarasov/get-tag@v2.1
      id: tagName
      if: startsWith(github.ref, 'refs/tags/')
      with:
        tagRegex: "v(.*)"
        tagRegexGroup: 1
    - uses: actions/checkout@v3
    - name: Setup MSBuild
      uses: microsoft/setup-msbuild@v1
    - name: Compile
      shell: bash
      run:
         |
        for FILE in *.cs
        do
            csc.exe "$FILE" /win32icon:"MScholtes.ico"
        done
    - name: Get release tag (tagged)
      if: startsWith(github.ref, 'refs/tags/')
      shell: bash
      run: echo "RELEASE_NAME=${{ steps.tagName.outputs.tag }}" >> $GITHUB_ENV
    - name: Get release tag (manual)
      if: startsWith(github.ref, 'refs/tags/') == false
      shell: bash
      run: echo "RELEASE_NAME=${{ github.event.inputs.tag_name }}" >> $GITHUB_ENV
    - name: Create Release
      uses: softprops/action-gh-release@v1
      with:
        files: "*.exe" 
        tag_name: "${{ env.RELEASE_NAME }}"
        name: "${{ env.RELEASE_NAME }}"